# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "line for firebase distribution"
  lane :distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart"
    firebase_app_distribution(
    app: "1:496767650256:android:fb23e92a14019a475751d5",
    firebase_cli_token:ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type:"APK",
    android_artifact_path:"../build/app/outputs/apk/production/release/app-production-release.apk",
  
    testers: "ma7080642@gmail.com",
    release_notes: "Lots of amazing new features to test out!"
  )
  end
end
